### ISSUE TITLE
Mussi & al. - Melka Kunture

### ISSUE THREAD

**Issue by secretaire-scientifique** [secretaire-scientifique/AE35-Current-Archaeology#9]
Article originally sent to the AE-36. Article well structured and written, but as no archives have been mobilized, it appears better to pass it in the Current Archaeology project. 
[MUSSI et al._60 years at Melka Kunture_with ref.docx](https://github.com/secretaire-scientifique/AE35-Current-Archaeology/files/11634852/MUSSI.et.al._60.years.at.Melka.Kunture_with.ref.docx)

Figures have been sent separatly to the coordinators with a wetransfer link.

**Comment by carolinerobionbrunner** [comment]
Blade et Yonas ont accepté de faire les relectures

**Comment by carolinerobionbrunner** [comment]
Blade rendra son avis après la mi-juillet
Yonas début juillet

**Comment by carolinerobionbrunner** [comment]
Yonas a envoyé son évaluation le 6 aout. On attend celle de Blade
[AE_evaluation_form-7.pdf](https://github.com/secretaire-scientifique/AE35-Current-Archaeology/files/12546378/AE_evaluation_form-7.pdf)
